version: '3'

services:
  database:
    image: mongodb/mongodb-atlas-local:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - ./docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - '8025:8025' # web ui
      - '1025:1025' # smtp server
